#### NumPy arrays, operations, broadcasting, and Pandas ,DataFrames, Series, indexing, and data grouping.

In [9]:
import numpy as np;
import pandas as pd;

marks = np.array([65, 72, 88, 91, 56, 79, 84, 95, 68, 73])
print(marks)

[65 72 88 91 56 79 84 95 68 73]


In [ ]:
import numpy as np                  

arr = np.array([10, 20, 30, 40, 50])
print(arr[2])          #Indexing
print(arr[1:4])        #Slicing


30
[20 30 40]


In [ ]:
arr = np.array([10, 20, 30, 40])     #Array operation
print(arr*2)

[20 40 60 80]
